// Codurile de eroare canonice (docs/ERROR_CODES.md, invarianta 3.10).
// Frontend mapeaza codul la mesaje localizate; `message` din raspuns e doar fallback.

export const ERROR_CODES = {
  // Generale
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  SESSION_SUPERSEDED: 'SESSION_SUPERSEDED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_INVALID_CODE: 'TWO_FACTOR_INVALID_CODE',

  // Companii
  COMPANY_NOT_APPROVED: 'COMPANY_NOT_APPROVED',
  COMPANY_SUSPENDED: 'COMPANY_SUSPENDED',
  COMPANY_REAPPLY_BLOCKED: 'COMPANY_REAPPLY_BLOCKED',
  CUI_ALREADY_REGISTERED: 'CUI_ALREADY_REGISTERED',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  LAST_OWNER_CANNOT_LEAVE: 'LAST_OWNER_CANNOT_LEAVE',

  // Cereri
  DRAFT_TOKEN_INVALID: 'DRAFT_TOKEN_INVALID',
  REQUEST_NOT_EDITABLE: 'REQUEST_NOT_EDITABLE',
  EDIT_LIMIT_PRE_CLAIM_REACHED: 'EDIT_LIMIT_PRE_CLAIM_REACHED',
  EDIT_LIMIT_POST_CLAIM_REACHED: 'EDIT_LIMIT_POST_CLAIM_REACHED',
  EDIT_BLOCKED_OFFER_RECEIVED: 'EDIT_BLOCKED_OFFER_RECEIVED',
  REQUEST_EXPIRED: 'REQUEST_EXPIRED',
  REPOST_ALREADY_USED: 'REPOST_ALREADY_USED',
  GEOCODING_FAILED: 'GEOCODING_FAILED',
  CONFIGURATOR_ANSWERS_INVALID: 'CONFIGURATOR_ANSWERS_INVALID',
  CONFIGURATOR_FLOW_VERSION_UNSUPPORTED: 'CONFIGURATOR_FLOW_VERSION_UNSUPPORTED',
  CONFIGURATOR_STATE_TOO_LARGE: 'CONFIGURATOR_STATE_TOO_LARGE',

  // Claim
  CLAIM_NOT_ALLOWED: 'CLAIM_NOT_ALLOWED',
  CLAIM_SLOTS_FULL: 'CLAIM_SLOTS_FULL',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  OUT_OF_COVERAGE_AREA: 'OUT_OF_COVERAGE_AREA',
  GATING_NOT_OPEN: 'GATING_NOT_OPEN',
  COMPANY_EXCLUDED_FROM_REQUEST: 'COMPANY_EXCLUDED_FROM_REQUEST',
  ACTIVE_CLAIM_WITHOUT_OFFER_EXISTS: 'ACTIVE_CLAIM_WITHOUT_OFFER_EXISTS',
  MANAGER_UNASSIGNED_CAP_REACHED: 'MANAGER_UNASSIGNED_CAP_REACHED',
  ASSIGNED_USER_HAS_ACTIVE_CLAIM: 'ASSIGNED_USER_HAS_ACTIVE_CLAIM',
  ASSIGNED_USER_PENALTY_BLOCKED: 'ASSIGNED_USER_PENALTY_BLOCKED',
  CLAIM_ALREADY_EXISTS: 'CLAIM_ALREADY_EXISTS',

  // Retrageri
  WITHDRAWAL_REASON_NOT_VALIDATED: 'WITHDRAWAL_REASON_NOT_VALIDATED',
  WITHDRAWAL_ALREADY_PENDING: 'WITHDRAWAL_ALREADY_PENDING',
  WITHDRAWAL_GRACE_EXPIRED: 'WITHDRAWAL_GRACE_EXPIRED',
  WITHDRAWAL_ALREADY_DECIDED: 'WITHDRAWAL_ALREADY_DECIDED',
  CLAIM_NOT_WITHDRAWABLE: 'CLAIM_NOT_WITHDRAWABLE',
  REQUEST_NOT_DELETABLE: 'REQUEST_NOT_DELETABLE',

  // Oferte
  QUOTE_VERSION_LIMIT_REACHED: 'QUOTE_VERSION_LIMIT_REACHED',
  QUOTE_ALREADY_SENT: 'QUOTE_ALREADY_SENT',
  CHANGE_REQUEST_ALREADY_REJECTED: 'CHANGE_REQUEST_ALREADY_REJECTED',
  CHANGE_REQUEST_NOT_PENDING: 'CHANGE_REQUEST_NOT_PENDING',
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  QUOTE_WITHDRAW_WINDOW_CLOSED: 'QUOTE_WITHDRAW_WINDOW_CLOSED',
  VALIDITY_EXTENSION_LIMIT_REACHED: 'VALIDITY_EXTENSION_LIMIT_REACHED',
  OFFER_FIELD_NOT_EDITABLE: 'OFFER_FIELD_NOT_EDITABLE',
  CONSULTATION_INVITE_EXPIRED: 'CONSULTATION_INVITE_EXPIRED',
  NEGOTIATION_ENDED: 'NEGOTIATION_ENDED',
  QUOTE_ACCEPT_NOT_ALLOWED: 'QUOTE_ACCEPT_NOT_ALLOWED',

  // Chat / upload
  THREAD_READ_ONLY: 'THREAD_READ_ONLY',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_LIMIT_REACHED: 'FILE_LIMIT_REACHED',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_SCAN_BLOCKED: 'FILE_SCAN_BLOCKED',
  UPLOAD_NOT_FOUND_IN_STORAGE: 'UPLOAD_NOT_FOUND_IN_STORAGE',

  // SLA / clarificari
  CLARIFICATION_ALREADY_PENDING: 'CLARIFICATION_ALREADY_PENDING',
  SLA_ALREADY_BREACHED: 'SLA_ALREADY_BREACHED',

  // Plati / credite
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_ALREADY_CONFIRMED: 'PAYMENT_ALREADY_CONFIRMED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  CREDIT_PACKAGE_INACTIVE: 'CREDIT_PACKAGE_INACTIVE',
  CREDITS_EXPIRED: 'CREDITS_EXPIRED',

  // Livrare / finalizare
  DELIVERY_NOT_ALLOWED: 'DELIVERY_NOT_ALLOWED',
  COMPLETION_NOT_ALLOWED: 'COMPLETION_NOT_ALLOWED',

  // Review / dispute
  REVIEW_NOT_ALLOWED_YET: 'REVIEW_NOT_ALLOWED_YET',
  REVIEW_ALREADY_SUBMITTED: 'REVIEW_ALREADY_SUBMITTED',
  DISPUTE_ALREADY_DECIDED: 'DISPUTE_ALREADY_DECIDED',

  // Admin
  SETTING_KEY_UNKNOWN: 'SETTING_KEY_UNKNOWN',
  AUDIT_LOG_IMMUTABLE: 'AUDIT_LOG_IMMUTABLE',
  ADMIN_DECISION_REQUIRED_FIELDS: 'ADMIN_DECISION_REQUIRED_FIELDS',

  // Inspiratie / colectii
  BOARD_NAME_TAKEN: 'BOARD_NAME_TAKEN',

  // Studio 3D / drafturi in cont
  STUDIO_DRAFT_NAME_TAKEN: 'STUDIO_DRAFT_NAME_TAKEN',
  STUDIO_DRAFT_LIMIT_REACHED: 'STUDIO_DRAFT_LIMIT_REACHED',
  STUDIO_DRAFT_INVALID: 'STUDIO_DRAFT_INVALID',
  STUDIO_DRAFT_TOO_LARGE: 'STUDIO_DRAFT_TOO_LARGE',

  // Auth — L0-A (reset/schimbare parola, termeni)
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  TERMS_NOT_ACCEPTED: 'TERMS_NOT_ACCEPTED',
  // L0-B — integritate business (2026-08-19)
  // cererea nu mai primeste oferte (status in afara CLAIMED_*/OFFERS_RECEIVED/NEGOTIATION sau stearsa)
  REQUEST_NOT_OPEN_FOR_OFFERS: 'REQUEST_NOT_OPEN_FOR_OFFERS',
  // conflict de concurenta la scriere (serialization failure P2034) — clientul poate reincerca
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
    timestamp: string;
    traceId: string;
  };
}
